version: '3'

services:
  postgres:
    image: postgres:13.6
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  blockscout:
    image: aiax-blockscout
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        COIN: "AXX"
        JSON_RPC: "https://test-rpc.aiax.network"
        NETWORK_PATH: "/"
        COIN_NAME: "Aiax"
        SUBNETWORK: "AIAX Testnet"
        CHAIN_ID: "789621341"
    restart: unless-stopped
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    env_file:
      -  ./envs/aiax-blockscout.env
    depends_on:
      - postgres

  reproxy:
    image: umputun/reproxy
    volumes:
      - ./reproxy/acme:/var/acme
    restart: unless-stopped
    ports:
      - 80:8080
      - 443:8443
    environment:
      - STATIC_ENABLED=True
      - STATIC_RULES=aiaxscan.com,^/(.*),http://blockscout:4000/$$1
      - SSL_TYPE=auto
      - SSL_ACME_LOCATION=/var/acme
      - TIMEOUT_RESP_HEADER=30
    depends_on:
      - blockscout
